import{a as b,S as v,N as c,i as M}from"./assets/vendor-Cebg-7dP.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function f(r,n=1,a=15){const i="https://pixabay.com/api/",e="48018775-66f870a0a55ddc658d7ca6c06",t=new URLSearchParams({key:e,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a});console.log("API request:",`${i}?${t}`);try{const s=await b.get(`${i}?${t}`);return console.log("Successful API response:",s.data),s}catch(s){throw console.error("API request error:",s),s}}const o={galleryDiv:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),form:document.querySelector(".search-form"),input:document.querySelector('.search-form input[name="searchQuery"]')};o.galleryDiv||console.error("Gallery not found in DOM");o.loadMoreBtn||console.error("Load More button not found in DOM");o.form||console.error("Form not found in DOM");o.input||console.error("Input field not found in DOM");function w(){o.galleryDiv.innerHTML=""}function p(r){o.galleryDiv.insertAdjacentHTML("beforeend",N(r))}function N(r){return r.map(({webformatURL:n,largeImageURL:a,tags:i,likes:e,views:t,comments:s,downloads:L})=>`
        <div class="photo-card">
          <a href="${a}" class="gallery-image">
            <img src="${n}" alt="${i}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes: ${e}</b></p>
            <p class="info-item"><b>Views: ${t}</b></p>
            <p class="info-item"><b>Comments: ${s}</b></p>
            <p class="info-item"><b>Downloads: ${L}</b></p>
          </div>
        </div>
        `).join("")}let l=1;const u=15,m=document.getElementById("loading-indicator"),y=()=>m.style.display="block",g=()=>m.style.display="none",d=()=>{var r;return(r=o==null?void 0:o.loadMoreBtn)==null?void 0:r.classList.add("load-more-hidden")},S=()=>{var r;return(r=o==null?void 0:o.loadMoreBtn)==null?void 0:r.classList.remove("load-more-hidden")};d();const h=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:200});document.addEventListener("DOMContentLoaded",()=>{c.Notify.init({position:"right-bottom",clickToClose:!0,timeout:3e3})});async function B(r){var a,i;r.preventDefault();const n=o.input.value.trim();if(!n){d(),c.Notify.failure("Please enter a search query.");return}l=1,w(),y(),c.Notify.info("Loading images, please wait.");try{const e=await f(n,l,u);if(!((i=(a=e==null?void 0:e.data)==null?void 0:a.hits)!=null&&i.length)){M.error({title:"Error",message:"No images found."});return}const t=e.data.totalHits;t>u?S():d(),c.Notify.success(`Success! Found ${t} images.`),p(e.data.hits),h.refresh()}catch{c.Notify.failure("An error occurred. Please try again.")}finally{g()}}async function D(){var n,a;l+=1;const r=o.input.value.trim();y(),c.Notify.info("Loading more images, please wait.");try{const i=await f(r,l,u);if(!((a=(n=i==null?void 0:i.data)==null?void 0:n.hits)!=null&&a.length)){d(),c.Notify.failure("No more results.");return}p(i.data.hits),h.refresh();const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{c.Notify.failure("An error occurred while loading more images.")}finally{g()}}o!=null&&o.form&&o.form.addEventListener("submit",B);o!=null&&o.loadMoreBtn&&o.loadMoreBtn.addEventListener("click",D);
//# sourceMappingURL=index.js.map
