import{a as b,S as M,N as c,i as v}from"./assets/vendor-Cebg-7dP.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function f(i,a=1,s=15){const r="https://pixabay.com/api/",e="48018775-66f870a0a55ddc658d7ca6c06",o=new URLSearchParams({key:e,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:s});console.log("API request:",`${r}?${o}`);try{const n=await b.get(`${r}?${o}`);return console.log("Successful API response:",n.data),n}catch(n){throw console.error("API request error:",n),n}}const t={galleryDiv:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),form:document.querySelector(".search-form"),input:document.querySelector('.search-form input[name="searchQuery"]')};t.galleryDiv||console.error("Gallery not found in DOM");t.loadMoreBtn||console.error("Load More button not found in DOM");t.form||console.error("Form not found in DOM");t.input||console.error("Input field not found in DOM");function w(){t.galleryDiv.innerHTML=""}function p(i){t.galleryDiv.insertAdjacentHTML("beforeend",P(i))}function P(i){return i.map(({webformatURL:a,largeImageURL:s,tags:r,likes:e,views:o,comments:n,downloads:L})=>`
        <div class="photo-card">
          <a href="${s}" class="gallery-image">
            <img src="${a}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes: ${e}</b></p>
            <p class="info-item"><b>Views: ${o}</b></p>
            <p class="info-item"><b>Comments: ${n}</b></p>
            <p class="info-item"><b>Downloads: ${L}</b></p>
          </div>
        </div>
        `).join("")}let d=1;const u=15,m=document.getElementById("loading-indicator"),y=()=>m.style.display="block",g=()=>m.style.display="none",l=()=>{var i;return(i=t==null?void 0:t.loadMoreBtn)==null?void 0:i.classList.add("load-more-hidden")},N=()=>{var i;return(i=t==null?void 0:t.loadMoreBtn)==null?void 0:i.classList.remove("load-more-hidden")};l();const h=new M(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:200});document.addEventListener("DOMContentLoaded",()=>{c.Notify.init({position:"right-bottom",clickToClose:!0,timeout:3e3})});async function S(i){var s,r;i.preventDefault();const a=t.input.value.trim();if(!a){l(),c.Notify.failure("Please enter a search query.");return}d=1,w(),y(),c.Notify.info("Loading images, please wait.");try{const e=await f(a,d,u);if(!((r=(s=e==null?void 0:e.data)==null?void 0:s.hits)!=null&&r.length)){l(),v.error({title:"Error",message:"No images found."});return}const o=e.data.totalHits;Math.ceil(o/u)>d?N():l(),c.Notify.success(`Success! Found ${o} images.`),p(e.data.hits),h.refresh()}catch{l(),c.Notify.failure("An error occurred. Please try again.")}finally{g()}}async function B(){var a,s;d+=1;const i=t.input.value.trim();y(),c.Notify.info("Loading more images, please wait.");try{const r=await f(i,d,u);if(!((s=(a=r==null?void 0:r.data)==null?void 0:a.hits)!=null&&s.length)){l(),c.Notify.failure("No more results.");return}p(r.data.hits),h.refresh();const e=r.data.totalHits,o=Math.ceil(e/u);d>=o&&l();const{height:n}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}catch{l(),c.Notify.failure("An error occurred while loading more images.")}finally{g()}}t!=null&&t.form&&t.form.addEventListener("submit",S);t!=null&&t.loadMoreBtn&&t.loadMoreBtn.addEventListener("click",B);
//# sourceMappingURL=index.js.map
